---
descriptor-schema-version: "2.7"

info:
  name: "iox_aarch64_hello"
  description: "simple docker hellow world app for arm64v8"
  version: "1.0"
  author-link: "http://www.wwt.com"
  author-name: "Joel W. King"

app:
  cpuarch: "aarch64"
  type: "docker"
  resources:
    profile: c1.tiny
    network:
      -
        interface-name: eth0
        ports:
          tcp: ["9000"]

  startup:
    rootfs: rootfs.tar
    target: ["python","hello.py"]